### ISSUE TITLE
Missing documentation for delete?

### ISSUE THREAD

**Issue by r3wt** [cloudinary/cloudinary_npm#128]
How exactly do you delete images? can i delete by secure_url? Its the only thing i'm storing in db.. If not, no worries, easy to obtain the id from the secure url i assume.

**Comment by taragano** [comment]
The deletion API methods require the image's `public_id`, rather than its full URL.
If the `resource_type` isn't `image`, or the `type` isn't `upload` then you need to also pass those to the deletion parameters as well. For more information:
http://cloudinary.com/documentation/node_image_upload#update_and_delete_images
http://cloudinary.com/documentation/admin_api#delete_resources

**Comment by r3wt** [comment]
@taragano thank you.
