### ISSUE TITLE
Enhancement for 'Generating video thumbnails'.

### ISSUE THREAD

**Issue by Minoga** [cloudinary/cloudinary_npm#173]
I use https://cloudinary.com/documentation/video_manipulation_and_delivery#generating_video_thumbnails (Node.js) for generating video thumbnail.  If i generate thumbnail with width then i get something like `<img src='http://res.cloudinary.com/dmsydx1hz/video/upload/w_60/v1/wahl-eiendom-bolig-2/pyhvkjrhcnrjqcae2oqk.jpg' width='60'/>`. I should use regexp to get `src` and i should use original width and height to get height that conform to new width. Is there api to get this information easier way? It would be nice to return object with necessary information.

**Comment by yakirp** [comment]
Hi @Minoga ,
Regarding the URL generate - consider using `.url()` instead of `.image()`:
`cloudinary.url("{public_id}", {resource_type: "video" , width : "60"})`

Do note that when you specify the width in the URL, we generating the image with the appropriate height:
[http://res.cloudinary.com/demo/video/upload/w_60/dog.jpg](http://res.cloudinary.com/demo/video/upload/w_60/dog.jpg)

Is that what you meant?

Yakir

**Comment by Minoga** [comment]
Thx, @yakirp. `.url()` is suitable. 
But height is needed as before. We have react component for thumbnail and it requires `width` and `height` .

**Comment by yakirp** [comment]
Hi @Minoga ,

In order to calculate the `height` of the image, you need to know/set the aspect ratio. 
This is the formula: `height = width / aspect ratio`

For example, here I set the aspect ratio to `16:9` :
http://res.cloudinary.com/demo/video/upload/ar_16:9,w_60/dog.jpg

So height = 60 / (16:9), which is 35.

Best,
Yakir

**Comment by roeeba** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
