### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by ATakaSKY** [cloudinary/cloudinary_npm#269]
I am trying to upload an array of images to cloudinary but getting 403. Here is the code that I am using:

```
import cloudinary from 'cloudinary';

cloudinary.config({ 
  cloud_name: '####', 
  api_key: '####', 
  api_secret: '####'
});

exports.submitForm = async (req, res) => {
    let filePathArray = [];

   //files are already parsed with multer
    if (req.files) {
        for(const file of req.files){
            filePathArray.push(`${req.protocol}://${req.get('host')}/files/${Date.now()}-${file.originalname}`);
        }
    }

    filePathArray.forEach(async (file,index) => {
        try{
            const result = await cloudinary.v2.uploader.upload(file);   
        }
        catch(err){
            console.log(err);
        }
        
    })
}
```

The error that I am getting is below:

```
{ message: 'Error in loading http://localhost:4201/files/1558601597380-icons.jpg - 403 Forbidden',
  http_code: 400 }
{ message: 'Error in loading http://localhost:4201/files/1558601597380-Silverlight.png - 403 Forbidden',
  http_code: 400 }
{ message: 'Error in loading http://localhost:4201/files/1558601597380-Skills_500.png - 403 Forbidden',
  http_code: 400 }
```

**Comment by cloudinaraz** [comment]
@ATakaSKY please note that the URLs you are passing to the upload method are from your localhost server.
When uploading an image from a remote URL, our servers are trying to reach the provided URL and retrieve the image from there. This means the URL needs to be resolvable externally, which is of course not possible with localhost.
When running in production, with a publicly accessible domain name, you shouldn't encounter this 403 error.
Alternatively, you can use the local path to the file on your server e.g. /path/to/file.jpg, to upload the file directly from your server instead of telling our servers to fetch it from the remote URL.
