### ISSUE TITLE
[Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by isaacSolano** [cloudinary/cloudinary_npm#287]
Got the following code, and getting the issue [Error: ENOENT: no such file or directory, on the req.body I have the path of the files, like "image.png", not the full path like "folder/folder/image.png", here's my code

const express = require('express'),
    router = express.Router(),
    multerUploads = require('../middleware/multer.config'),
    cloudinary = require('cloudinary').v2,
    cloudinaryconfig = require('../middleware/cloudinary.config'),
    PublicacionModel = require('./publicaciones.model');

    cloudinary.config({
        cloud_name: cloudinaryconfig.cloud_name,
        api_key: cloudinaryconfig.api_key,
        api_secret: cloudinaryconfig.api_secret,
    })

router.route('/registrar_publicacion')
    .post( multerUploads, (req, res) => {

        console.log(req.body);
        for(let i=0; i<req.body.length; i++){
            let imagePath = req.body[i].path;

            cloudinary.uploader.upload(imagePath, (err, res) => {
                console.log(res);
                console.log(err);
            })
            
        }

**Comment by michalkcloudinay** [comment]
Hi @isaacSolano ,
In order to upload images via the API in Node.js, you need to specify the full path of the media file to upload.
Looking at your request on [issue 172](https://github.com/cloudinary/cloudinary_npm/issues/172) it seems that you only have the name of the file and not the full path which can indeed be the issue.

We would be happy to assist further if you could share more details about the implementation.
For example, where are you receiving the files from?
What is the value of `imagePath`?

Any further information that you find relevant would also help us
 
If privacy is a concern,  please open a ticket with us at support@cloudinary.com.

**Comment by strausr** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
