### ISSUE TITLE
cloudinary not working when login

### ISSUE THREAD

**Issue by anonystick** [cloudinary/cloudinary_npm#300]
I see
cloudinary not working when login
<img width="1836" alt="Screen Shot 2019-09-20 at 4 45 33 PM" src="https://user-images.githubusercontent.com/48472372/65317518-30c90a00-dbc6-11e9-82be-ce5339507b45.png">

**Comment by aleksandar-cloudinary** [comment]
Hi @anonystick . Looking at the logs on our end I can see that you've renamed your cloud name today and from your screenshot, it is showing the old cloud name. It is advisable to logout and back in after renaming your cloud in order to invalidate any stale sessions/references to the old cloud. If you rename your account without logging out and back in then you can also run into errors during uploads. Let me know if it works for your after logout/login.

**Comment by strausr** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
