### ISSUE TITLE
Delete multiple files problem (delete_resources / destroy)

### ISSUE THREAD

**Issue by PFittech** [cloudinary/cloudinary_npm#320]
Hello, Can someone help me, please? How I can delete one and more images from cloudinary in node.js? I try this:

```
const cloudinary = require('cloudinary').v2;
cloudinary.config({ 
  cloud_name: 'franek', 
  api_key   : '***', 
  api_secret: '***' 
});
```

`  cloudinary.api.delete_resources(ids, (error, result) => {
    console.log(result, error)
  });`
NOT WORKING

```
cloudinary.uploader.destroy(ids, { invalidate: true, resource_type: 'image' }, (error, result) => {
    console.log(result, error)
  });
```
ALSO NOT WORKING

**where I try 2 variants of ids:**

A: 
[ https://res.cloudinary.com/franek/image/upload/v1575129481/labbka/file_e9tfyg.webp,
 https://res.cloudinary.com/franek/image/upload/v1575129481/labbka/file_lsb0i5.webp ]

B: 
[ labbka/file_e9tfyg, labbka/file_lsb0i5 ]

Response 1:
```
{
  deleted: {
    'http://res.cloudinary.com/franek/image/upload/v1575132580/labbka/file_e9tfyg.webp': 'not_found',
    'http://res.cloudinary.com/franek/image/upload/v1575132587/labbka/file_lsb0i5.webp': 'not_found'
  },
  deleted_counts: {
    'http://res.cloudinary.com/franek/image/upload/v1575132580/labbka/file_e9tfyg.webp': { original: 0, derived: 0 },
    'http://res.cloudinary.com/franek/image/upload/v1575132587/labbka/file_lsb0i5.webp': { original: 0, derived: 0 }
  },
  partial: false,
  rate_limit_allowed: 500,
  rate_limit_reset_at: 2019-11-30T18:00:00.000Z,
  rate_limit_remaining: 497
} undefined
```

Response 2:
 ```
undefined { message: 'Missing required parameter - public_id', http_code: 400 }
{"message":"Missing required parameter - public_idMissing required parameter - public_id","http_code":400,"level":"error"}
```

**Comment by aleksandar-cloudinary** [comment]
Hi @PFittech. When using the [delete resources](https://cloudinary.com/documentation/admin_api#delete_resources) method of the Admin API then you can indeed pass an array of public_ids to delete (variant B). I don't see any requests to the Admin API, but I can see the failed [destroy](https://cloudinary.com/documentation/image_upload_api_reference#destroy_method) method calls. Variant A is invalid and won't work for any API calls that is why Request 1 fails. Unlike the delete resources method, the destroy only takes a single public_id and your requests were passing an array which is why those failed.

If you want to use the Admin API then your request should look like this;

```
var ids = [ "labbka/file_e9tfyg", "labbka/file_lsb0i5" ];

cloudinary.api.delete_resources(
    ids,
    function(error, result) {
        console.log(result, error)
    }
);
```

Alternatively, passing each ID to the destroy method (resource_type defaults to image so you won't need to pass that unless it's different);

```
cloudinary.uploader.destroy(
    "labbka/file_e9tfyg",
    {
        invalidate: true
    }, 
    function(error, result) {
        console.log(result, error)
    }
);
```

Please try this out and let me know how it goes.

**Comment by aleksandar-cloudinary** [comment]
Hi @PFittech. When using the [delete resources](https://cloudinary.com/documentation/admin_api#delete_resources) method of the Admin API then you can indeed pass an array of public_ids to delete (variant B). Variant A is invalid and won't work for any API calls and that is why Request 1 fails. I can also see the failed [destroy](https://cloudinary.com/documentation/image_upload_api_reference#destroy_method) method calls. Unlike the delete resources method, the destroy only takes a single public_id and your requests were passing an array (variant B) which is why those failed.

If you want to use the Admin API then your request should look like this;

```
var ids = [ "labbka/file_e9tfyg", "labbka/file_lsb0i5" ];

cloudinary.api.delete_resources(
    ids,
    function(error, result) {
        console.log(result, error)
    }
);
```

Alternatively, passing each ID to the destroy method (resource_type defaults to image so you won't need to pass that unless it's different);

```
cloudinary.uploader.destroy(
    "labbka/file_e9tfyg",
    {
        invalidate: true
    }, 
    function(error, result) {
        console.log(result, error)
    }
);
```

Please try this out and let me know how it goes.

**Comment by PFittech** [comment]
@aleksandar-cloudinary thank you, You solved my problem. Maybe a quick question why I see **undefined** in response?

```
 {
   deleted: { 'labbka/file_nvjm2i': 'deleted' },
   deleted_counts: { 'labbka/file_nvjm2i': { original: 1, derived: 0 } },
   partial: false,
   rate_limit_allowed: 500,
   rate_limit_reset_at: 2019-12-01T07:00:00.000Z,
   rate_limit_remaining: 497
 } undefined
```

**Comment by aleksandar-cloudinary** [comment]
@PFittech No problem at all. The undefined in the response corresponds to the 'error' variable that is returned in the callback and is printed at the same time as the 'result'. As the API call didn't produce any errors the 'result' is printed and 'error' is undefined. For example, if you look at your Response 2 in the initial post, you'll notice that the 'result' is undefined and 'error ' has a value. `undefined { message: 'Missing required parameter - public_id', http_code: 400 }`

**Comment by promiselxg** [comment]
@aleksandar-cloudinary thanks.
