### ISSUE TITLE
Getting cross origin issue due to user-agent in Mozilla and Safari Browser in Chrome Wroking

### ISSUE THREAD

**Issue by Niravdjoshi** [cloudinary/cloudinary_npm#364]
cloudinary.uploader.upload(imageUrl, { colors: true },
      function (error, result) {
        if (result) {
        console.log(result)
       } else {
          console.log(error)
        }
      })

I'm getting cross origin error in  mozilla and safari browser in due to 'user-agent' in header it's working fine in chrome browser. 
When I removed ''user-agent' then it's working .

**Comment by aleksandar-cloudinary** [comment]
Hi @NRVdjoshi. In general, but especially from server-side uploads like in your case, you shouldn't be getting any issues relating to CORS from Cloudinary. Server-side uploads won't experience that issue since the upload is done directly and not via a `XMLHttpRequest` or Fetch API request. However, even in cases the upload is done from the client-side via `XMLHttpRequest` or Fetch API the browser would automatically set the required Origin header which Cloudinary would return in the response to the CORS OPTIONS request as an allowed Origin.

As I understand, you have a frontend that takes input, you forward that data to your server and perform the upload from there, is that right? If not, may I please ask you to share more details or a page on your site we can access to reproduce the issue? If that's not possible, could you please share a screenshot of the error and provide some details on how your website/app takes a file for upload and processes it outside the code snippet?

Also, what happens if you just run the code snippet you shared directly from your server by specifying a local file for upload, does the file upload correctly? if not, what is the `error`?

**Comment by Niravdjoshi** [comment]
It''s working fine after I have change request in server-side earlier I'm facing issue on client side.
