### ISSUE TITLE
Missing Typescript type declarations for at least "delete_folder" and "create_folder"

### ISSUE THREAD

**Issue by vdupre** [cloudinary/cloudinary_npm#460]
## Describe the bug in a sentence or two.

At least 2 type declarations are missing: 
- [v2.api.delete_folder](https://cloudinary.com/documentation/admin_api#delete_folder) 
- [v2.api.create_folder](https://cloudinary.com/documentation/admin_api#create_folder)

The code itself is working well with a ts-ignore :+1: 

## Issue Type
[ ] Build - Can’t install or import the SDK
[ ] Babel - Babel errors or cross browser issues
[ ] Performance - Performance issues
[ ] Behaviour - Functions aren’t working as expected (Such as generate URL)
[ ] Documentation - Inconsistency between the docs and behaviour
[x] Incorrect Types - For typescript users who are having problems with our d.ts files
[ ] Other (Specify)

## Versions and Libraries
Cloudinary_NPM SDK version - 1.23.0
Node - 13.10.1
NPM - 6.13.7

**Comment by igy** [comment]
Thanks for reporting this - we're aware that the typescript files in the current version of the SDK don't currently cover everything

I discussed this with our SDK team recently and we're currently working on a new major version of the Node SDK, which will be built in Typescript from the beginning, and so that the team can focus on that, we're not planning to make edits to the 1.x versions to add further typescript definitions.

I recommend subscribing to this Github repository or our product updates page to see when a 2.X version of the SDK is released, and this which should have ~100% support for type checking. 

Apologies if this causes any problems for you in the short term, but once the new SDK is ready it should be fully type checked and not require any ts-ignore directive for your case

**Comment by vdupre** [comment]
@igy ok, no problem, thanks for the answer and good luck with the new version then :) 

And if I may, if you are building a new major version, 2 suggestions maybe:
- switch to promise instead of callback
- use camel case

**Comment by cloudinaraz** [comment]
Hey @vdupre, we are working on a completely new major release of the Node SDK that will consist of some breaking changes, including retiring callbacks entirely for promises and using camel cases as you've mentioned. 

I believe this is the answer you were hoping for 🙂.
