### ISSUE TITLE
Unable to view uploaded pdf file via cloudinary url after successful file upload

### ISSUE THREAD

**Issue by neymarjimoh** [cloudinary/cloudinary_npm#478]
## Describe the bug in a sentence or two.
After i upload files from nodejs api, I'm unable to view the file from the browser using the generated url from cloudinary. it works smoothly for other file types but i'm currently facing this issue when uploading a pdf file.
…

## Issue Type (Can be multiple)
Behaviour - Functions aren’t working as expected (Such as generate URL)

## Steps to reproduce
… if applicable

## Error screenshots
… if applicable

## Versions and Libraries (fill in the version numbers)
Cloudinary_NPM SDK version
Node - 14.15.4
NPM - 6.14.10

## Config Files (Please paste the following files if possible)
Package.json
![cld](https://user-images.githubusercontent.com/45770371/109033965-6f21fd00-76c7-11eb-988b-8f9d1d7c6a9b.JPG)

## Repository
If possible, please provide a link to a reproducible repository that showcases the problem

**Comment by eyalktCloudinary** [comment]
Hey @neymarjimoh, thanks for reaching out!
Due to a recent update to our security policies, we've added a restriction on deliveries of PDF and Archive files for new accounts. This is most probably the reason you cannot view the PDF files using their URLs. If you want this restriction to be removed, feel free to reach out via a [support ticket](https://support.cloudinary.com/hc/en-us/requests/new), and in case the issue turns out to be not related to the restriction, we could further investigate via the ticket. 

Additional information about the restriction can be found [here](https://support.cloudinary.com/hc/en-us/articles/360016480179-PDF-or-ZIP-files-appearing-in-Media-Library-but-download-URLs-return-an-error-).
