### ISSUE TITLE
Cloudinary return this message when i'm trying to upload image. "Must supply api_key"

### ISSUE THREAD

**Issue by asyncfinkd** [cloudinary/cloudinary_npm#570]
## Describe the bug in a sentence or two.
so when i'm trying to upload image in cloudinary image library. server return text like this: "Must supply api_key", also i'm using nestjs.

let's take a look my environments and small code what i'm using (specially i'm using 'xxx' for hide my cloudinary secret keys).

```jsx
import { v2 } from 'cloudinary';

export const CloudinaryProvider = {
  provide: 'Cloudinary',
  useFactory: (): void => {
    return v2.config({
      cloud_name: 'xxx',
      api_key: 'xxx',
      api_secret: 'xxx',
    });
  },
};
```

this is code part for upload image function.

```jsx
import { Injectable } from '@nestjs/common';
import { UploadApiErrorResponse, UploadApiResponse, v2 } from 'cloudinary';
import toStream = require('buffer-to-stream');

@Injectable()
export class CloudinaryService {
  async uploadImage(
    file: any,
  ): Promise<UploadApiResponse | UploadApiErrorResponse> {
    return new Promise((resolve, reject) => {
      const upload = v2.uploader.upload_stream((error, result) => {
        if (error) return reject(error);
        resolve(result);
      });

      toStream(file.buffer).pipe(upload);
    });
  }
}
```

Thanks, for interesting.

## Browsers (if issue relates to UI, else ignore)
[x] All

## Versions and Libraries (fill in the version numbers)
Cloudinary_NPM SDK version - 1.31.0
Node - 16.18.0
NPM - 8.19.2

**Comment by tamaracloudinary** [comment]
Hi there,

Thanks for getting in touch. May I please ask for some more information?
Can you please confirm the cloud name of the account you're using?

The 'must supply api_key' error implies that we're not receiving the correct cloud name and API key in the API call made by your app.

Are you sure that the exact values are being set correctly and that the correct values are being used by the SDK? Does it work if you configure the SDK with the CLOUDINARY_URL instead of using the exact variables?

If you don't want to share credentials here, please open a new private support ticket [here](https://support.cloudinary.com/hc/en-us/requests/new). 

Thanks, 
Tamara

**Comment by asyncfinkd** [comment]
It was very confusing. now it's working thanks for helping.

i'll close this issue.
