### ISSUE TITLE
Missing`upload_stream` documentation

### ISSUE THREAD

**Issue by nk9** [cloudinary/cloudinary_npm#628]
## Bug report for Cloudinary NPM SDK
The only reference to `upload_stream` in the documentation is [this example](https://cloudinary.com/documentation/upload_images#upload_data_stream). It doesn't show up in the [Upload API reference](https://cloudinary.com/documentation/image_upload_api_reference#signed_upload_syntax) which means there's no explanation of what the various parameters/options are, what's returned, caveats to its use, etc. I spent a great deal of time trying to figure out how to upload a string to a file, ultimately arriving at [an upload stream wrapped in a `Promise`](https://community.cloudinary.com/discussion/349/why-are-some-of-my-uploads-silently-failing-the-first-time-or-two) after reading [this GitHub issue](https://github.com/cloudinary/cloudinary_npm/issues/130). But it was far more confusing than it needed to be.

Note also that the example in the first link above uses the streamifier library when I think it's possible to just use a normal Node `Readable`. In my case, I was actually able to pass the string I wanted uploaded directly to `.end()`, so I didn't even need to create the stream myself.

It would be great to have some discussion of asynchronous considerations using streams in the documentation you write for `upload_stream`, even if all you do is mention that stream operations are always asynchronous and point to some MDN docs about how to properly use them. Bonus points for a Promise implementation, or some distillation of [this comment](https://github.com/cloudinary/cloudinary_npm/issues/130#issuecomment-417933120).

## Describe the bug in a sentence or two.
Missing documentation for `upload_stream`

## Issue Type (Can be multiple)
[ ] Build - Can’t install or import the SDK
[ ] Babel - Babel errors or cross browser issues
[ ] Performance - Performance issues
[ ] Behaviour - Functions aren’t working as expected (Such as generate URL)
[x] Documentation - Inconsistency between the docs and behaviour
[ ] Incorrect Types - For typescript users who are having problems with our d.ts files
[ ] Other (Specify)

**Comment by skalahasti-cloudinary** [comment]
Hi @nk9,

Thanks for sharing your documentation feedback with us!

That’s a great point and we’ve opened a documentation ticket to fix this and will get back to you when this is considered and fixed.

We are continually working to improve our docs' developer/user experience, and we appreciate your input.

Best regards,
Sreenath

**Comment by raae** [comment]
I would also like to point out that the documentation for regular upload states that the file param can be an array buffer, leading to confusion, as mentioned in as well https://github.com/cloudinary/cloudinary_npm/issues/130

![CleanShot 2023-10-03 at 13 07 09@2x](https://github.com/cloudinary/cloudinary_npm/assets/478531/9d1c1dfb-53c3-4eec-aa69-82e46ee53b85)

**Comment by tommyg-cld** [comment]
@nk9  upload stream docs can now be found here https://cloudinary.com/documentation/node_image_and_video_upload#node_js_upload_stream

@raae so if you click `For details and examples, see: file source options.`, it has more info on `Upload data stream` with a link to our node.js SDK implementation as well. 

any questions, let me know.

**Comment by nk9** [comment]
Thanks for this, especially the quick turnaround. I'm curious, though: is there a reason that the method is still missing from the API documentation?

https://cloudinary.com/documentation/image_upload_api_reference#unsigned_upload_syntax

I understand that it may be called different things in different SDKs (it looks like the equivalent is `upload_large` in Python for some reason), but isn't that all the more reason for the various options to be enumerated in the API documentation?

**Comment by tommyg-cld** [comment]
@nk9 upload_stream is a method only specific to the nodejs SDK at the moment, it uses the upload API but since it is not directly a REST API endpoint, it's not included in that page. It is in our roadmap to make this function available on all the other SDKs but there is no ETA.

We have included it in the nodejs docs per https://cloudinary.com/documentation/node_image_and_video_upload#node_js_upload_stream

Regarding upload_large, it is a separate method to which also uses upload API to upload large files in chunks, more here: https://cloudinary.com/documentation/upload_images#chunked_asset_upload. This method is available on all our SDKs and not Python specific. 

Please let me know if you have any other questions or queries.

**Comment by tommyg-cld** [comment]
@nk9 upload_stream is a method only specific to the nodejs SDK at the moment, it uses the upload API but since it is not directly a REST API endpoint, it's not included in that page.

Please note per https://cloudinary.com/documentation/upload_images#upload_data_stream, you can upload a data stream using the standard upload method for all the other SDKs, it's only node.js that requires a dedicated method at the moment.

We have included it in the nodejs docs per https://cloudinary.com/documentation/node_image_and_video_upload#node_js_upload_stream

Regarding upload_large, it is a separate method to which also uses upload API to upload large files in chunks, more here: https://cloudinary.com/documentation/upload_images#chunked_asset_upload. This method is available on all our SDKs and not Python specific.

Please let me know if you have any other questions or queries.
