### ISSUE TITLE
Explicit upload eager transform doesn't match generated url transform

### ISSUE THREAD

**Issue by eugmill** [cloudinary/cloudinary_npm#685]
## Bug report for Cloudinary NPM SDK
Before proceeding, please update to latest version and test if the issue persists
✅ On version 2.4.0

## Describe the bug in a sentence or two.
When I upload a pdf with `cloudinary.uploader.explicit` and eager transforms, and then fetch that same pdf with the same transforms using `cloudinary.v2.url` , I get two derived assets and the 2nd one has an extra slash at the end. 

## Issue Type (Can be multiple)
[ ] Build - Can’t install or import the SDK
[ ] Babel - Babel errors or cross browser issues
[ ] Performance - Performance issues
[x] Behaviour - Functions aren’t working as expected (Such as generate URL)
[ ] Documentation - Inconsistency between the docs and behaviour
[ ] Incorrect Types - For typescript users who are having problems with our d.ts files
[ ] Other (Specify)

## Steps to reproduce
1. Upload a pdf 
2. Call `v2.uploader.explicit` with the following transformations passed to `eager` with `eager_async` true: 
```
[
  {
    "density": 150,
    "flags": [
      "rasterize",
      "tiled"
    ]
  },
  {
    "angle": -56,
    "crop": "scale",
    "effect": "anti_removal",
    "opacity": 17,
    "overlay": {
      "font_family": "FuturaPTDemi.otf",
      "font_size": 100,
      "text": "John%20Doe"
    },
    "flags": [
      "relative",
      "no_overflow",
      "layer_apply"
    ],
    "width": "1.0"
  }
]
```
3. Call `v2.url` with the same publicId. `sign_url` should be `true`, `type` should be authenticated and `transformation` should be the same array as step 2.

4. Fetch the url

If you get the derived assets for the public id, you can see 2 different derived assets with 2 different transformations
Eager loaded:
```
"dn_150,fl_rasterize.tiled/a_-56,c_scale,e_anti_removal,fl_relative.no_overflow.layer_apply,l_text:FuturaPTDemi.otf_100:John%20Doe,o_17,w_1.0"
```
Lazy generated
```
"dn_150,fl_rasterize.tiled/a_-56,c_scale,e_anti_removal,fl_relative.no_overflow.layer_apply,l_text:FuturaPTDemi.otf_100:John%20Doe,o_17,w_1.0/"
```

Expected behavior: The url returns the derived asset from the eager call.
Actual behavior: The url generates a new derived asset.

## Error screenshots
… if applicable

## Browsers (if issue relates to UI, else ignore)
[ ] Chrome
[ ] Firefox
[ ] Safari
[ ] Other (Specify)
[x] All

## Versions and Libraries (fill in the version numbers)
Cloudinary_NPM SDK version
Node - 18.7.1
NPM - 9.6.7

## Config Files (Please paste the following files if possible)
Package.json

## Repository
If possible, please provide a link to a reproducible repository that showcases the problem

**Comment by tommyg-cld** [comment]
@eugmill I see you opened a ticket for this so lets continue using the ticket but adding the answer here for reference. 

It seems when you generate the URL for the asset, you do it without the file extension e.g. https://demo-res.cloudinary.com/image/upload/sample which is why you see `"dn_150,fl_rasterize.tiled/a_-56,c_scale,e_anti_removal,fl_relative.no_overflow.layer_apply,l_text:FuturaPTDemi.otf_100:John%20Doe,o_17,w_1.0/"`. Notice the trailing slash at the end, this means the derived asset was generated without an extension whereas in your explicit call, you don't end with a trailing slash so a derived version with the original file extension is generated. 
 
You can: 
 
1. Generate the URL with the extension (pass the public_id as j0bjdqogz5ijg37znxby.pdf in this case) OR
2. Generate a derived with a trailing slash (no extension)

**Comment by eugmill** [comment]
That was totally it. Thank you, I appreciate the quick response!
