### ISSUE TITLE
How to get an image's versioned url, by public id

### ISSUE THREAD

**Issue by ismay** [cloudinary/cloudinary_npm#85]
I've seen issue #35, and I was wondering whether something similar can be done to fetch the versioned (secure) url of an image via it's public id (with the cloudinary lib). I'd like to integrate this in my build system so I can replace references to a public id with the versioned urls.

**Comment by taragano** [comment]
When uploading images, Cloudinary immediately returns the uploaded image's details, including its `public_id`, `version`, and more. We recommend storing the `version` at the upload response phase. Otherwise, for already uploaded images, you can access the [Admin API](http://cloudinary.com/documentation/admin_api#browse_resources) to get the image's details.

Note that the version component is optional, the URLs will work well without it too. The version component is offered for use for cases where you override images and you need to bypass CDN cached versions of the image. For more information:
http://cloudinary.com/documentation/upload_images#image_versions

**Comment by taragano** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support http://support.cloudinary.com or create a new ticket if you have any additional issues
